# Generated by Django 3.0 on 2019-12-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191217_0736'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Polls',
            new_name='Choice',
        ),
    ]
